baseURL = "http://mindpalace.xyz"
languageCode = "en-us"
title = "Mind Palace"
theme = "book"
BookTheme = "dark"
enableEmoji = "true"
BookMenuBundle = '/menu'
RelativeURLs = "false"
CanonifyURLs = "false"
[markup.goldmark.renderer]
unsafe= true