baseURL = "https://mindpalace.xyz"
languageCode = "en-us"
title = "Mind Palace"
theme = "book"
BookTheme = "dark"
enableEmoji = "true"
BookMenuBundle = '/menu'
# RelativeURLs = "false"
# CanonifyURLs = "true"
# [markup.goldmark.renderer]
# unsafe= true
exclude = "./README.md"